### ISSUE TITLE
Documentation to Upload RHCOS to AWS AMI is out-of-date

### ISSUE THREAD

**Issue by johnsimcall** [jaredhocutt/openshift4-deploy#38]
It appears that simply following the example commands from docs/rhcos.md will result in failure, because the examples show RHCOS 4.3.8 (which didn't work for Mike when trying to deploy with openshift_version 4.3.18)

Consider using .../latest/latest/... in the ```wget``` example.

**Comment by jaredhocutt** [comment]
@johnsimcall For clarification, did Mike attempt to use `4.3.18` as the RHCOS version and that's why it didn't work?

**Comment by johnsimcall** [comment]
Yes, it appears that by following **exactly** the rhcos.md and vars/ocp4.example.yml file he ended up with a 4.3.8 RHCOS + openshift_version 4.3.18 which failed to progress beyond ```openshift-install wait-for bootstrap-complete```

**Comment by jaredhocutt** [comment]
RHCOS 4.3.8 is the latest version and should work correctly.

Here is a snippet from `docs/rhcos.md` that I stole from the OpenShift docs:

>Download the highest version that is less than or equal to the OpenShift
>version you are installing. For example, if you are installing OpenShift
>`4.3.18` and the latest RHCOS available is `4.3.8`, then use RHCOS `4.3.8`.

Therefore, using RHCOS 4.3.8 would be the correct version for OpenShfit 4.3.18.

I'm assuming you filed this issue because there was something you did to workaround whatever issue you hit? Can you share those details?

**Comment by johnsimcall** [comment]
I don't know if I workaround the issue necessarily...  I did a fresh pull of master and used Mike's AWS GovCloud credentials to successfully deploy in both ```us-gov-west-1``` and ```us-gov-east-1``` regions.  Here is the successful vars file:

```
# cat vars/mflanner-govcloud-east.yml 
---

cloud: aws_govcloud
openshift_version: 4.4.3

cluster_name: ocp4
base_domain: example.com

rhcos_ami: ami-0c9b747d # US-Gov-East-1 RHCOS 4.4.3
#rhcos_ami: ami-71866900 # US-Gov-East-1 RHCOS 4.3.8
keypair_name: mflanner
keypair_path: ~/.ssh/id_rsa-mflanner-govcloud

pull_secret: ''
```

**Comment by jaredhocutt** [comment]
My guess is that the RHCOS 4.3.8 image was being used to install OpenShift 4.4.3, which isn't likely to work. Instead, you would need to use the RHCOS 4.4.3 image, which it appears you ended up doing and were able to get a successful install.

I'm going to keep this issue open because there are likely some additional wording that could be added to the doc to make it more clear that you cannot blindly copy/paste the command and do need to update the versions to match the environment you are attempting to install.
